captainVersion: 4
caproverOneClickApp:
    instructions:
      start: Setting up LAMP Stack for CapRover
      end: LAMP Stack for CapRover deployed.
########
services:
  cpvlabpro:
    image: protomated/cpv-lab-pro:latest
