captainVersion: 4
caproverOneClickApp:
    instructions:
      start: Setting up LAMP Stack for CapRover
      end: LAMP Stack for CapRover deployed.
########
services:
  cpvlabpro:
    image: ghcr.io/protomated/cpv-lab-pro:latest@sha256:ac5f26d12634878e21731bbc535777e3dbf3f8a33e3c00eb26b32c758b4b70f0